version: '3'

volumes:
    data:

services:
    db:
        image: postgres
        volumes:
            - data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASS}

    web:
        #        restart: always
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile
        command: python ./src/manage.py runserver 0.0.0.0:8000
        depends_on:
            - db
        ports:
            - "8000:8000"
        volumes:
            - ./:/app/
            - ./uwsgi.ini:/app/uwsgi.ini