# Generated by Django 3.2 on 2022-05-26 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=124)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidade', models.IntegerField()),
                ('situacao', models.SmallIntegerField(choices=[(0, 'Indisponível'), (1, 'Disponível')])),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('solicitante', models.CharField(max_length=124)),
                ('solicitante_endereco', models.CharField(max_length=360)),
                ('despachante', models.CharField(max_length=124)),
                ('situacao', models.SmallIntegerField(choices=[(0, 'Pendente de Envio'), (1, 'Enviado'), (3, 'Entregue')])),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='produtos.produto')),
            ],
        ),
    ]
